import { Activite } from "@/types/activite";

export const ActiviteData: Activite[] = [
  {
    id: 1,
    path: "activite/1",
    images: [
      "/images/activite/1/activite1-1.png",
      "/images/activite/1/activite1-2.png",
      "/images/activite/1/activite1-3.png",
      "/images/activite/1/activite1-4.JPG",
    ],
    name: "Bivouac",
    description: "Vivez une aventure authentique en pleine nature avec notre bivouac à Tafraout ! Installez-vous sous les étoiles au milieu des paysages spectaculaires de l'Anti-Atlas, entre rochers granitiques, palmeraies et villages berbères. Ce séjour en plein air vous permet de déconnecter du quotidien, de partager des moments conviviaux autour d'un feu de camp, et de découvrir la culture locale dans un cadre unique et paisible.",
    contact: {
      nom: "anti-atlas aventures",
      email: "antiatlas.aventures@gmai.com",
      tel: "06664308848",
      whatsapp: "0672779936",
    },
    rating: 0,
    location: "Tafraout",
    siegeSocial: "Red de chausser immeuble Boukhssim",
    site: "anti-atlas-venentures.com",
  },
  {
    id: 2,
    path: "activite/2",
    images: [
      "/images/activite/2/activite2-1.png",
      "/images/activite/2/activite2-2.png",
      "/images/activite/2/activite2-3.png",
      "/images/activite/2/activite2-4.png",
      "/images/activite/2/activite2-5.png",
      "/images/activite/2/activite2-6.png",
    ],
    name: "Canyoning",
    description: "Pour les amoureux du canyonisme, sport de pleine nature apparenté à la randonnée pédestre, à l'escalade et à l'alpinisme, les terres amazighes de Tafraout offrent une descente amusante au bout des gorges et des falaises pour des sensations fortes pour le bonheur des amateurs de ce sport.",
    contact: {
      nom: "anti-atlas aventures",
      email: "antiatlas.aventures@gmai.com",
      tel: "06664308848",
      whatsapp: "0672779936",
    },
    rating: 0,
    location: "Tafraout",
    siegeSocial: "Red de chausser immeuble Boukhssim",
    site: "anti-atlas-venentures.com",
  },
  {
    id: 3,
    path: "activite/3",
    images: [
      "/images/activite/3/activite3-1.png",
      "/images/activite/3/activite3-2.png",
      "/images/activite/3/activite3-3.png",
      "/images/activite/3/activite3-4.png",
      "/images/activite/3/activite3-5.png",
      "/images/activite/3/activite3-6.png",
    ],
    name: "Escalade",
    description: "Réputée pour ses impressionnantes formations rocheuses, Tafraout est une destination incontournable pour les passionnés d’escalade. La région offre une grande variété de falaises adaptées aussi bien aux grimpeurs débutants qu’aux experts, avec des itinéraires classés selon différents niveaux de difficulté. Nichée au cœur de l’Anti-Atlas, elle propose certains des parcours d’ascension les plus spectaculaires et les plus aventureux du Maroc, fréquemment mentionnés dans les guides spécialisés.",
    contact: {
      nom: "anti-atlas aventures",
      email: "antiatlas.aventures@gmai.com",
      tel: "06664308848",
      whatsapp: "0672779936",
    },
    rating: 0,
    location: "Tafraout",
    siegeSocial: "Red de chausser immeuble Boukhssim",
    site: "anti-atlas-venentures.com",
  },
  {
    id: 4,
    path: "activite/4",
    images: [
      "/images/activite/4/activite4-1.jpeg",
      "/images/activite/4/activite4-2.jpeg",
      "/images/activite/4/activite4-3.jpeg",
      "/images/activite/4/activite4-4.jpeg",
    ],
    name: "Bivouac",
    description: "vous êtes à Tafraout ? Tafraout est l'un des meilleurs endroits recommandés pour le parapente dans la région de Souss. Les touristes viennent y chercher les sensations fortes du parapentisme sur les sommets d'Idiki, de Tagdicht, de Foghal ou d'autres. Un sport pour profiter du séjour et jouir de la vue panoramique de Tafraout autrement.",
    contact: {
      nom: "anti-atlas aventures",
      email: "antiatlas.aventures@gmai.com",
      tel: "06664308848",
      whatsapp: "0672779936",
    },
    rating: 0,
    location: "Tafraout",
    siegeSocial: "Red de chausser immeuble Boukhssim",
    site: "anti-atlas-venentures.com",
  },
  {
    id: 5,
    path: "activite/5",
    images: [
      "/images/activite/5/activite5-1.jpg",
      "/images/activite/5/activite5-2.jpg",
      "/images/activite/5/activite5-3.HEIC",
      "/images/activite/5/activite5-4.HEIC",
      "/images/activite/5/activite5-5.jpg",
    ],
    name: "randonnée",
    description: "Destination par excellence des randonnées pédestres, Tafraout est l'une des villes marocaines qui offre un panorama de paysages formidables que vous pouvez découvrir en vous promenant au milieu des vallées et des villages pour vous imprégner de la richesse du patrimoine naturel et culturel qui font la beauté de cette région. Des offres et des formules de randonnée variées selon la durée, la distance et le niveau de difficulté sont proposées aux visiteurs.",
    contact: {
      nom: "anti-atlas aventures",
      email: "antiatlas.aventures@gmai.com",
      tel: "06664308848",
      whatsapp: "0672779936",
    },
    rating: 0,
    location: "Tafraout",
    siegeSocial: "Red de chausser immeuble Boukhssim",
    site: "anti-atlas-venentures.com",
  },
  {
    id: 6,
    path: "activite/6",
    images: [
      "/images/activite/6/activite6-1.jpg",
      "/images/activite/6/activite6-2.HEIC",
      "/images/activite/6/activite6-3.HEIC",
    ],
    name: "VTT",
    description: "Il est recommandé de découvrir la beauté naturelle en VTT. Nous offrons plusieurs itinéraires en VTT qui dévoilent les trésors cachés de Tafraout. Nous enfourchons les vélos pour commencer un superbe rald autour des villages choisis. En roulant sur les routes tranquilles, nous allons traverser des villages berbères avec une architecture à l'ancienne. Une formule 3 en 1 détendez-vous, pratiquez du sport et découvrez Tafraout.",
    contact: {
      nom: "anti-atlas aventures",
      email: "antiatlas.aventures@gmai.com",
      tel: "06664308848",
      whatsapp: "0672779936",
    },
    rating: 0,
    location: "Tafraout",
    siegeSocial: "Red de chausser immeuble Boukhssim",
    site: "anti-atlas-venentures.com",
  },
  {
    id: 7,
    path: "activite/7",
    images: [
      "/images/activite/7/activite7-1.jpeg",
      "/images/activite/7/activite7-2.jpeg",
      "/images/activite/7/activite7-3.webp",
      "/images/activite/7/activite7-4.jpeg",
    ],
    name: "Yoga et méditation",
    description: "Plongez dans l'apaisement à Tafraout, un Joyau naturel idéal pour les passionnés de yoga et de méditation. Ses vastes paysages offrent une évasion parfaite, alliant la quiétude naturelle à la pratique revitalisante du bien-être. Découvrez l'harmonie à Tafraout, où la tranquillité rencontre la méditation.",
    contact: {
      nom: "anti-atlas aventures",
      email: "antiatlas.aventures@gmai.com",
      tel: "06664308848",
      whatsapp: "0672779936",
    },
    rating: 0,
    location: "Tafraout",
    siegeSocial: "Red de chausser immeuble Boukhssim",
    site: "anti-atlas-venentures.com",
  },

];

export default ActiviteData;
